import { Platform } from 'react-native'

const HORIZONTAL_SPACING_BASE = Platform.OS === 'web' ? 4 : 2
const VERTICAL_SPACING_BASE = 4

const icons = {
  logo: require('../assets/icons/logo.png'),
  userAvatar: require('../assets/icons/default-avatar.jpg'),
  menuHamburger: require('../assets/icons/hamburger-menu-icon.png'),
  backArrow: require('../assets/icons/arrow-back-icon.png'),
  close: require('../assets/icons/close-x-icon.png'),
  home: require('../assets/icons/home.png'),
  categories: require('../assets/icons/categories.png'),
  collections: require('../assets/icons/collections.png'),
  commentUnfilled: require('../assets/icons/comment-unfilled.png'),
  commentFilled: require('../assets/icons/comment-filled.png'),
  compose: require('../assets/icons/compose.png'),
  filter: require('../assets/icons/filter.png'),
  filters: require('../assets/icons/filters.png'),
  heart: require('../assets/icons/heart.png'),
  heartFilled: require('../assets/icons/heart-filled.png'),
  map: require('../assets/icons/map.png'),
  search: require('../assets/icons/search.png'),
  review: require('../assets/icons/review.png'),
  list: require('../assets/icons/list.png'),
  starFilled: require('../assets/icons/star_filled.png'),
  starNoFilled: require('../assets/icons/star_nofilled.png'),
  logout: require('../assets/icons/shutdown.png'),
  rightArrow: require('../assets/icons/right-arrow.png'),
  accountDetail: require('../assets/icons/account-detail.png'),
  wishlistFilled: require('../assets/icons/wishlist-filled.png'),
  orderDrawer: require('../assets/icons/order-drawer.png'),
  settings: require('../assets/icons/settings.png'),
  contactUs: require('../assets/icons/contact-us.png'),
  delete: require('../assets/icons/delete.png'),
  communication: require('../assets/icons/communication.png'),
  cameraFilled: require('../assets/icons/camera-filled.png'),
  send: require('../assets/icons/send.png'),
  emptyAvatar: require('../assets/icons/empty-avatar.jpg'),
  checklist: require('../assets/icons/checklist.png'),
  homeUnfilled: require('../assets/icons/home-unfilled.png'),
  homefilled: require('../assets/icons/home-filled.png'),
  search: require('../assets/icons/search.png'),
  magnifier: require('../assets/icons/magnifier.png'),
  profileUnfilled: require('../assets/icons/profile-unfilled.png'),
  profileFilled: require('../assets/icons/profile-filled.png'),
  camera: require('../assets/icons/camera.png'),
  cameraFilled: require('../assets/icons/camera-filled.png'),
  inscription: require('../assets/icons/inscription.png'),
  more: require('../assets/icons/more.png'),
  send: require('../assets/icons/send.png'),
  pinpoint: require('../assets/icons/pinpoint.png'),
  checked: require('../assets/icons/checked.png'),
  bell: require('../assets/icons/bell.png'),
  heartUnfilled: require('../assets/icons/heart-unfilled.png'),
  cameraRotate: require('../assets/icons/camera-rotate.png'),
  libraryLandscape: require('../assets/icons/library-landscape.png'),
  playButton: require('../assets/icons/play-button.png'),
  logout: require('../assets/icons/logout-drawer.png'),
  delayedLogo: require('../assets/icons/delaylogo.png'),
  blockedUser: require('../assets/icons/blocked-user-64.png'),
}

const lightColors = {
  primaryBackground: '#ffffff',
  secondaryBackground: '#ffffff',
  primaryForeground: '#42eb89',
  secondaryForeground: '#8442bd',
  foregroundContrast: 'white',
  primaryText: '#151723',
  secondaryText: '#7e7e7e',
  hairline: '#e0e0e0',
  grey0: '#fafafa',
  grey3: '#f5f5f5',
  grey6: '#d6d6d6',
  grey9: '#939393',
  red: '#ea0606',
}

const InstamobileTheme = {
  colors: {
    light: lightColors,
    'no-preference': lightColors,
    dark: {
      primaryBackground: '#121212',
      secondaryBackground: '#000000',
      primaryForeground: '#42eb89',
      secondaryForeground: '#8442bd',
      foregroundContrast: 'white',
      primaryText: '#ffffff',
      secondaryText: '#c5c5c5',
      hairline: '#222222',
      grey0: '#0a0a0a',
      grey3: '#2a2a2a',
      grey6: '#f5f5f5',
      grey9: '#eaeaea',
      red: '#ea0606',
    },
  },
  spaces: {
    horizontal: {
      s: 2 * HORIZONTAL_SPACING_BASE,
      m: 4 * HORIZONTAL_SPACING_BASE,
      l: 6 * HORIZONTAL_SPACING_BASE,
      xl: 8 * HORIZONTAL_SPACING_BASE,
    },
    vertical: {
      s: 2 * VERTICAL_SPACING_BASE,
      m: 4 * VERTICAL_SPACING_BASE,
      l: 6 * VERTICAL_SPACING_BASE,
      xl: 8 * VERTICAL_SPACING_BASE,
    },
  },
  fontSizes: {
    xxs: 8,
    xs: 12,
    s: 14,
    m: 16,
    l: 18,
    xl: 24,
    xxl: 32,
  },
  fontWeights: {
    s: '400',
    m: '600',
    l: '800',
  },
  icons: icons,
  // color, font size, space / margin / padding, vstack / hstack
  button: {
    borderRadius: 8,
  },
}

export default InstamobileTheme
